# =========================================================
# UMC Mogi Das cruzes
# Programador: Paulo Ricardo De Sousa7
# Data: 30/03/2023
# Programa: Volume do Cilindro
# ==========================================================
Rai = float(input('Digite o raio da base em centimetro ='))
Alt = float(input('Digite a altura do cilindro em centimetro ='))
Pi = float(input('Digite o valor aproximado de pi ='))
Area = Pi*Rai**2
Volume = Area*Alt
print('O Volume do Cilindro é =', Volume)
