# ==================================================
# UMC Mogi Das Cruzes
# Programador: Paulo Ricardo De Sousa
# Data: 30/03/2023
# Programa: Média de três números
# ===================================================

Not1 = float(input('Digite a Primeira Nota ='))
Not2 = float(input('Digite a Segunda Nota ='))
Not3 = float(input('Digite a terceira Nota ='))
Media = (Not1+Not2+Not3)/2
print('A Média é = ', Media)

