# ==========================================
# UMC Mogi Das Cruzes
# Programador: Paulo Ricardo De Sousa
# Data: 30/03/2023
# Programa: Média Ponderada De três números
# ===========================================

Not1 = float(input('Digite a primeira nota ='))
Not2 = float(input('Digite a segunda nota ='))
Not3 = float(input('Digite a terceira nota ='))
Media = (Not1*2+Not2*3+Not3*5)/10
print('A Média Ponderada é =', Media)
