# =========================================
# UMC Mogi das Cruzes
# Programador: Paulo Ricardo De Sousa
# Data: 30/03/2023
# Programa: Cálculo da Formula
# =========================================

Nu1 = float(input('Digite o Primeiro número ='))
Nu2 = float(input('Digite o Segundo Númro ='))
Form= (-Nu1+((Nu2-Nu1)+(-Nu2)*Nu1)+20)
print ('Nu1 = %.2f \nNu2 = %.2f \nCálculo da Fórmula igual a = %.2f' % (Nu1,Nu2,Form))

